// The single serverless function behind every /api/* request (see vercel.json for the rewrite).
// The code lives in api/_server.mjs, generated by `npm run build:api`.
export { default } from './_server.mjs'
